# A successful run of this action creates a staging repo at
# s01.oss.sonatype.org. Further manual steps are needed to complete
# publishing to Maven Central, see:
# https://central.sonatype.org/publish/release/#releasing-deployment-from-ossrh-to-the-central-repository-introduction

on:
  push:
    tags:
      - aws-native/v*.*.*
      - aws/v*.*.*
      - awsx/v*.*.*
      - aws-apigateway/v*.*.*
      - azure-native/v*.*.*
      - azuread/v*.*.*
      - docker/v*.*.*
      - eks/v*.*.*
      - gcp/v*.*.*
      - google-native/v*.*.*
      - kubernetes/v*.*.*
      - oci/v*.*.*
      - random/v*.*.*
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CHANGELOG_PENDING.md'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  OSSRH_REPO_URL: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

  # Include only last 8 hex digits of the key ID included, due to
  # limitations of gradle.
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}

  # Obtained by `gpg --armor --export-secret-key support@pulumi.com`.
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

  # Aka passphrase for the GPG key.
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

  GPR_USER: ${{ secrets.GPR_USER }}
  GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        provider:
        - aws
        - aws-native
        - aws-apigateway
        - awsx
        - azure-native
        - azuread
        - docker
        - eks
        - gcp
        - google-native
        - kubernetes
        - oci
        - random
    steps:
      - uses: actions/checkout@v2
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
      - run: make submodule_update
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
      - name: Fetch Tags
        run: git fetch --quiet --prune --unshallow --tags
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.3.1
        with:
          repo: pulumi/pulumictl
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
      - run: ./scripts/versions.sh | tee versions.txt
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
      - name: Setup versioning env vars
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
        run: cat versions.txt | tee $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
      - name: Publish Provider Java SDK
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        if: startsWith(github.ref, format('refs/tags/{0}/v', matrix.provider))
        with:
          arguments: publish
          build-root-directory: providers/pulumi-${{ matrix.provider }}/sdk/java
          gradle-version: 7.4.1
